name: GitHub Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n-v: [17.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.n-v }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.n-v }}
      - name: i s
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run jest
