name: GitHub Actions Demo
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-versio }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versio }}
          cache: 'npm'
      - name: i-s
        run: npm install
      - name: build project
        run: npm run build
      - name: unit test
        run: npm run jest
